### ISSUE TITLE
Obtaining input within a handler?

### ISSUE THREAD

**Issue by MostHated** [shaned24/crabbot-discord#6]
Is there a certain way to go about obtaining input from within a handler? Ex. A command is issued, the bot PM's me, asks me to input something, I do it, it replies back for more input, etc, etc

Here is how I would go about it in Python with the bot framework I was using:

```python
async def wp_email_check(self, ctx):
    def check(m):
        return m.author == ctx.message.author
    await ctx.send(text.email_capture_during_verification())  # -- This would send the text out "Please enter your email address"
    email = await self.bot.wait_for('message', check=check)   # -- Then this would start an async method which would listen for input 
```

What is the proper way to go about getting input with this system?
Thanks,
-MH

**Comment by MostHated** [comment]
Unless there is something built in that I am missing, I came across this, and I think it might work out ok from the little bit of testing I have tried.  https://github.com/tehstone/GoKyogre/blob/d36d833de2249590d86b4279d4ab4f2091625104/src/util/waitutils.go

I am hoping it does the job!
Thanks,
-MH

**Comment by shaned24** [comment]
This looks good, I was curious about how it has been done by others!

**Comment by MostHated** [comment]
I have yet to do any sort of extensive testing, but I brought it up with the creator if Disgord and it looks like he recently added something similar to the library, so that should work out well.
